name: release-please

on:
  push:
    branches:
      - main

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - name: release-please
        id: release
        uses: googleapis/release-please-action@v4
        with:
          token: ${{ secrets.PAT_WORKFLOWS }}

      - name: 🛒 Checkout repository
        if: ${{ steps.release.outputs.release_created }}
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          token: ${{ secrets.PAT_WORKFLOWS }}

      - name: ⚙️ Setup dotnet 10.0.x
        if: ${{ steps.release.outputs.release_created }}
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: '10.0.x'

      - name: 🧹 Clean
        if: ${{ steps.release.outputs.release_created }}
        run: dotnet clean -c Release && dotnet nuget locals all --clear

      - name: 🔁 Restore packages
        if: ${{ steps.release.outputs.release_created }}
        run: dotnet restore

      - name: 🛠️ Building library in release mode
        if: ${{ steps.release.outputs.release_created }}
        run: dotnet build -c Release --no-restore /p:UseSourceLink=true

      - name: 🗳️ Creating library package for release
        if: ${{ steps.release.outputs.release_created }}
        run: dotnet pack src/Atc.Rest.MinimalApi/Atc.Rest.MinimalApi.csproj -c Release --no-restore -o ${GITHUB_WORKSPACE}/packages

      - name: 📦 Push packages to NuGet
        if: ${{ steps.release.outputs.release_created }}
        run: |
          dotnet nuget push ${GITHUB_WORKSPACE}/packages/*.nupkg -k ${{ secrets.NUGET_KEY }} -s https://api.nuget.org/v3/index.json --skip-duplicate --no-symbols
